//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Filmes
    {
        public Filmes()
        {
            this.Papeis = new HashSet<Papeis>();
            this.Reviews = new HashSet<Reviews>();
            this.Studios = new HashSet<Studios>();
            this.Generos = new HashSet<Generos>();
        }
    
        public int FilmeID { get; set; }

        [Required(ErrorMessage = "O {0} é obrigatório")]
        [Display(Name = "Título")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "O {0} deve ter no mínimo 3 e no máximo 100 caracteres.")]
        public string Titulo { get; set; }

        [Display(Name = "Duração do filme")]
        public Nullable<int> Duracao { get; set; }

        [Range(1800,2100)]
        [Display(Name = "Ano de lançamento")]
        public Nullable<int> AnoLancamento { get; set; }
    
        public virtual ICollection<Papeis> Papeis { get; set; }
        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<Studios> Studios { get; set; }
        public virtual ICollection<Generos> Generos { get; set; }
    }
}
