//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }

        [Required(ErrorMessage = "O filme é obrigatório")]
        public int FilmeID { get; set; }

        [Range(0,10, ErrorMessage = "A {0} deve ser entre 0 e 10")]
        [Required(ErrorMessage = "A {0} é obrigatório")]
        public int Nota { get; set; }

        public string Resenha { get; set; }
    
        public virtual Filmes Filmes { get; set; }
    }
}
