//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Reviews
    {
        public int ReviewID { get; set; }
        public int FilmeID { get; set; }
        public int UserID { get; set; }
        public decimal Nota { get; set; }
        public string Resenha { get; set; }
    
        public virtual Filmes Filmes { get; set; }
    }
}
